# Generated by Django 5.1.4 on 2024-12-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модел:')),
                ('number', models.CharField(error_messages={'unique': 'Има бус с този номер!'}, max_length=20, unique=True, verbose_name='Номер:')),
                ('km', models.IntegerField(blank=True, null=True, verbose_name='Километри:')),
            ],
        ),
        migrations.CreateModel(
            name='Modifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
