# Generated by Django 5.1.4 on 2024-12-25 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('repairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifications',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='repairs.repairsession'),
        ),
    ]
