# Generated by Django 5.1.4 on 2024-12-24 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_rename_bus_modifications_session_and_more'),
        ('repairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifications',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='repairs.repairsession'),
        ),
    ]
